int p1=1;
int p2=2;
int p3=3;
int p4=4;
int p5=5;
int p6=6;
int p7=7;

void setup() {
pinMode(p1, OUTPUT);
pinMode(p2, OUTPUT);
pinMode(p3, OUTPUT);
pinMode(p4, OUTPUT);
pinMode(p5, OUTPUT);
pinMode(p6, OUTPUT);
pinMode(p7, OUTPUT);

}

void loop() {
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
///YA

digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);

digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);///INICIO
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);///INICIO
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);///INICIO
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(200);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(200);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(200);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(200);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(100);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(100);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(100);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(100);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(50);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(50);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(50);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(50);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(20);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(20);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(20);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(20);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);///INICIO//////////////////
digitalWrite(p1, LOW);
digitalWrite(p2, HIGH);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, HIGH);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, HIGH);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, HIGH);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, HIGH);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(5);

digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, HIGH);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, HIGH);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, HIGH);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, HIGH);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, HIGH);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, HIGH);
digitalWrite(p5, HIGH);
digitalWrite(p6, HIGH);
digitalWrite(p7, LOW);
delay(300);
digitalWrite(p1, LOW);
digitalWrite(p2, LOW);
digitalWrite(p3, LOW);
digitalWrite(p4, LOW);
digitalWrite(p5, LOW);
digitalWrite(p6, LOW);
digitalWrite(p7, LOW);
delay(300);

// CRR31B 28 40

}
